### ISSUE TITLE
Integrate with a Kotlin linter

### ISSUE THREAD

**Issue by u-ways** [propactive/propactive-demo#4]
It would be nice to have a linter to keep the project as consistent as possible. A widely popular Kotlin linter is [Pinterest's ktlint](https://github.com/pinterest/ktlint). It has a built-in rule sets, formatter tasks, reporters, and allows extension with custom rule sets and reporters.

#### Requirements
- Set CI to run the linter after tests has passed. (must be a Makefile recipe)
- Provide an `.editorconfig` to allow IDE users adhere to the standards for a smoother dev experience.

Please see [the user guide](https://pinterest.github.io/ktlint/) for further details.

**Comment by doriancodes** [comment]
I can take over this issue :)

**Comment by u-ways** [comment]
@doriancodes Awesome, this has now been assigned to you.

**Comment by u-ways** [comment]
@doriancodes just a heads up that recent similar work has been completed/accepted here: https://github.com/u-ways/kotlin-quarkus-realworld-example-app/pull/8

**Comment by doriancodes** [comment]
I have some questions:
- would you prefer to use a gradle plugin or the cli tool directly? 
- are you aware of [this problem](https://pinterest.github.io/ktlint/rules/configuration-ktlint/) of adding `.editoconfig` file for Intellij users :
  > Unfortunately [IntelliJ IDEA](https://www.jetbrains.com/idea/) has an [autoformat issue regarding .editorconfig](https://youtrack.jetbrains.com/issue/IDEA-242506). Due to this error an additional space is added between glob statements, resulting in [\*{kt, kts}] instead of [\*{kt,kts}]. The .editorconfig library used by ktlint [ignores sections after encountering a space in the list](https://github.com/editorconfig/editorconfig/issues/148). As a result, the rule is not applied on all files as documented in the [original ktlint issue](https://github.com/pinterest/ktlint/issues/762).
- do you want to run the ktlint command just to check if there are files that need formatting (so without autoformat feature)? If that's the case wouldn't make sense to run the ktlint command before the tests?

**Comment by doriancodes** [comment]
update: I just saw https://github.com/u-ways/kotlin-quarkus-realworld-example-app/pull/8/files and answers most of my questions :)

**Comment by u-ways** [comment]
@doriancodes glad to read it helped.
- Yes, please use the Gradle plugin.
- For the glob issue: Separating each glob seems to resolve the issue if I am not mistaken (i.e. `[{\*.kt,\*.kts}]` instead of `[*{kt,kts}]`). If that doesn't fix it, can you please advise how would you fix this? (I will look into this in my free time if it couldn't be resolved)
- Finally, it would be preferable to run the Ktlinter **after** all tests has passed. This way, the dev will only have to modify their ktlint issues once at the end instead of having to modify again after fixing their tests.

**Comment by doriancodes** [comment]
I found out this solution proposed https://pinterest.github.io/ktlint/rules/configuration-intellij-idea/ . It seems that there is a gradle task from the plugin to generate this configuration locally called `ktlintApplyToIdea`, do you want me to mention it in the README.md file?

**Comment by u-ways** [comment]
> I found out this solution proposed https://pinterest.github.io/ktlint/rules/configuration-intellij-idea/ . It seems that there is a gradle task from the plugin to generate this configuration locally called `ktlintApplyToIdea`, do you want me to mention it in the README.md file?

Awesome, yeah I have used this task before, and I recall there is a similar task that you can apply IDE-level too. I would suggest mentioning this in the `CONTRIBUTING.md`. 

Since I am working on improving the documentation, I will add this in my todo list since you already submitted a PR, and it looks great.

**Comment by u-ways** [comment]
@doriancodes If you're interested in contributing more, you can have a look at other **hacktoberfest** tickets in the following repositories please:

- [Propactive](https://github.com/propactive/propactive/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest+no%3Aassignee)
- [Propactive-demo](https://github.com/propactive/propactive-demo/issues?q=is%3Aissue+is%3Aopen+label%3Ahacktoberfest+no%3Aassignee)
- [kotlin-quarkus-realworld-example-app](https://github.com/u-ways/kotlin-quarkus-realworld-example-app/issues?q=is%3Aopen+label%3Ahacktoberfest+no%3Aassignee)

Thanks again for your help :)
